# Site settings
title: scnz
email: jason@scnz.co
url: https://scnz.me
description: "Jason Scanzoni is a product manager and startup engineer based out of Washington, DC."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jason Scanzoni
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/jscanzoni
  - title: instagram
    url: https://instagram.com/jscanzoni
  - title: twitter
    url: https://twitter.com/jscanzoni
  - title: linkedin
    url: https://www.linkedin.com/in/jscanzoni
  - title: github
    url: https://github.com/jscanzoni

# Postal address (add as many lines as necessary)
address:
  - line: 718 7th St NW
  - line: Washington, DC 20001

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
